name: Hello World
author: Carlos Haro
description: Envia un mensaje de saludo

inputs:
    who-to-greet:
        description: "Who to greet"
        required: true
        default: Carlos

outputs:
    time:
        description: "The greeting time"

runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.who-to-greet }}
