name: "Send a Slack Message"
author: carlosharo85
description: "Send a Slack message with workflow information"

inputs:
    slack-webhook:
        description: "Slack Webhook"
        required: true
    message:
        description: "Slack Message"
        required: true

runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.slack-webhook }}
        - ${{ inputs.message }}
